pull_request_rules:
  - name: Merge automatically when CI passes and PR is approved
    conditions:
      - conflict
    actions:
      comment:
        message: Your PR is in conflict, {{author}}. You should fix it.