pull_request_rules:
  - name: "Automatic merge when CI passes and approved"
    conditions:
      - "#approved-reviews-by>=1"
      - "check-success=mergify-check"
      - "base=main"
      - "label=rebase"
    actions:
      merge:
        method: rebase

  - name: "Automatic squash merge when CI passes and approved"
    conditions:
      - "#approved-reviews-by>=1"
      - "check-success=mergify-check"
      - "base=main"
      - "label=squash"
    actions:
      merge:
        method: squash