name: build-and-test

on:
  push:
    tags: '*'
    branches-ignore: # Pushes on these branches won't start a build
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore: # Pushes that change only these file won't start the workflow
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        jvm-version: [ 11, 17, 21 ]
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.jvm-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jvm-version }}

      - name: Grant execute permission for gradlew on Unix systems
        if: matrix.os != 'windows'
        run: chmod +x gradlew

      - name: Assemble
        run: ./gradlew assemble

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test

      - name: Check
        run: ./gradlew check

  mergify-check:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Final Check
        run: echo "All builds passed successfully!"