name: release-version
on:
  workflow_call:
  workflow_dispatch:

jobs:
  release-and-delivery:
    permissions:
      packages: write
    concurrency:
      group: release-and-delivery-${{ github.event.number || github.ref }}
    runs-on: ubuntu-latest
    outputs:
      release-status: ${{ env.release_status }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Get All Tags
        run: git fetch --tags -f

      - name: Find the version of Node from package.json
        id: node-version
        run: echo "version=$(jq -r .engines.node package.json)" >> $GITHUB_OUTPUT

      - name: Install Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ steps.node-version.outputs.version }}

      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
